### ISSUE TITLE
Export sorting doesn't work the same as Import sorting.

### ISSUE THREAD

**Issue by Torhal** [daidodo/format-imports-vscode#43]
I had expected exports to be sorted by the same criteria as imports, but discovered that only the barrel names are sorted.

Given
```
export * from "./t-named-file";
export * from "./z-named-file";
export * from "./a-named-file";
```
Nothing happens. If these were imports instead of exports, you'd see:
```
import * as aName from "./a-named-file";
import * as tName from "./t-named-file";
import * as zName from "./z-named-file";
```
Given:
```
export { Foo, Baz, Bar  } from "./some-file";
```
The export is correctly sorted as:
```
export { Bar, Baz, Foo } from "./some-file";
```
This is correct, as it is what also happens for imports.

**Comment by daidodo** [comment]
@Torhal, thanks for the feedback!

Details about how exports are formatted can be found [here](https://github.com/daidodo/format-imports-vscode/issues/6#issuecomment-619386911). And sorting exports by paths is not supported yet because the requirement isn't clear.

But I'm happy to discuss any suggestions from you.

**Comment by daidodo** [comment]
@Torhal - I'll close this issue since there isn't enough response to start a discussion. But feel free to re-open it once you have something in mind.
