### ISSUE TITLE
Option to set Semicolon False

### ISSUE THREAD

**Issue by valdeniomarinho** [daidodo/format-imports-vscode#55]
`"tsImportSorter.configuration.hasSemicolon": false`

**Comment by daidodo** [comment]
Hi @valdeniomarinho - Generally *import-sorter.json* and *package.json* are preferred to VSCode settings because they are portable. For example:

*import-sorter.json:*

```json
{
  "hasSemicolon": false
}
```

But you can still add the above line to VSCode and it should just work. If not, please share the logs under [Debug Mode](https://github.com/daidodo/format-imports-vscode/blob/master/CONTRIBUTING.md#debug-mode).

Thanks!

**Comment by daidodo** [comment]
Closing the issue if no further questions.
